version = "1.0"

[main]
name.en = "MLMMJ settings"
name.fr = "Paramètres MLMMJ"

    [main.general]
    name.en = "General"
    name.fr = "Général"
        [main.general.closedlist]
        ask.en = "Is the list closed for subscription?"
        type = "boolean"

        [main.general.prefix]
        ask.en = "Prefix for the Subject line of emails"
        type = "string"

        [main.general.footer]
        ask.en = "Footer content"
        type = "text"
        bind = "__INSTALL_DIR__/control/footer"

        [main.general.moderated]
        ask.en = "Should the list be moderated?"
        type = "boolean"

        #[main.general.users]
        #name.en = "User Management"
        #ask.en = "Manage users for different categories (owners, moderators, etc.) in YAML format"
        #type = "text"
        #bind = "__INSTALL_DIR__/users.yml"


    [main.moderation]
    name.en = "Moderation"
    name.fr = "Modération"
    visible = "moderated == true"

        [main.moderation.mods_mode]
        ask.en = "Select moderators update mode"
        type = "select"
        choices = {yunohost = "Automatic from Yunohost group", mlmmj = "MLMMJ list manually managed"}

        [main.moderation.mods_group]
        ask.en = "Select YunoHost group for automatic moderators update"
        type = "group"
        visible = "mods_mode == 'yunohost'"

        [main.moderation.moderators]
        ask.en = "List of moderators (one email per line)"
        type = "text"
        bind = "__INSTALL_DIR__/control/moderators"
        visible = "mods_mode == 'mlmmj'"
