version = "1.0"

[main]
name.en = "MLMMJ settings"
name.fr = "Paramètres MLMMJ"

    [main.general]
    name.en = "General"
    name.fr = "Général"

        [main.general.list_status]
        ask.en = "List Subscription Status"
        ask.fr = "Statut d'abonnement à la liste"
        help.en = "'open' allows anyone to subscribe or unsubscribe by email, 'closedlistsub' restricts new subscriptions, and 'closedlist' restricts both new subscriptions and unsubscriptions."
        help.fr = "'open' permet à tout le monde de s'abonner ou se désabonner par courriel, 'closedlistsub' restreint les nouveaux abonnements et 'closedlist' restreint à la fois les nouveaux abonnements et les désabonnements."
        type = "select"
        choices = {"open" = "open", "closedlistsub" = "closedlistsub", "closedlist" = "closedlist"}

        [main.general.whocanpost]
        ask.en = "Who is able to post on the list"
        ask.fr = "Qui est autorisé à publier sur la liste ?"
        help.en = "'all' allows anyone to post, 'subonlypost' allows only people who are subscribed to the list, and 'modonlypost' allows only moderators to post (see moderation section below)."
        help.fr = "'all' permet à n’importe qui de publier sur la liste, 'subonlypost' permet uniquement aux abonnés de publier, 'modonlypost' permet uniquement aux abonnés de publier (voir la section modération ci-dessous)."
        type = "select"
        choices = {"all" = "all", "subonlypost" = "subonlypost", "modonlypost" = "modonlypost"}

    [main.owners]
    name.en = "Owners"
    name.fr = "Propriétaires"

        [main.owners.owner]
        ask.en = "List owners (one email per line)"
        ask.fr = "Propriétaires de la liste (un email par ligne)"
        help.en = "Setting name: owner"
        help.fr = "Nom du paramètre : owner"
        type = "text"
        bind = "__INSTALL_DIR__/ynh/moderators.txt"
        
        [main.owners.notifysub]
        ask.en = "Should owners be notified of subcriptions and unsubscribtions to the list?"
        ask.fr = "Les propriétaire doivent-ils être notifiés des abonnements et désabonnements à la liste ?"
        help.en = "Setting name: notifysub"
        help.fr = "Nom du paramètre : notifysub"
        type = "boolean"

        [main.owners.submod]
        ask.en = "Should subscription to the list be accepted by owners?"
        ask.fr = "L’abonnement à la liste doit-il être accepté par les propriétaires?"
        help.en = "Setting name: submod"
        help.fr = "Nom du paramètre : submod"
        type = "boolean"

        [main.owners.submod_list]
        ask.en = "Optional: it is possible to delegate the acceptation of subscriptions to addresses other than those of the owners (one e-mail address per line if used)."
        ask.fr = "Facultatif : il est possible de déléguer l’acceptation des abonnements à d’autres adresses que celles des propriétaires (une adresse courriel par ligne si utilisé)"
        help.en = "Setting name: submod"
        help.fr = "Nom du paramètre : submod"
        type = "text"
        bind = "__INSTALL_DIR__/ynh/submod.txt"
        visible = "submod == 1"
        

    [main.moderation]
    name.en = "Moderation"
    name.fr = "Modération"

        [main.moderation.moderators]
        ask.en = "List moderators (one email per line)"
        ask.fr = "Modérateurs de la liste (une adresse courriel par ligne)"
        help.en = "Setting name: moderators"
        help.fr = "Nom du paramètre : moderators"
        type = "text"
        bind = "__INSTALL_DIR__/ynh/owner.txt"

        [main.moderation.modnonsubposts]
        ask.en = "Should all postings from people who are not allowed to post to the list will be moderated instead of denied?"
        ask.fr = "Tous les messages provenant de personnes qui ne sont pas autorisées à publier sur la liste devraient-ils être modérés au lieu d'être refusés ?"
        help.en = "Setting name: modnonsubposts"
        help.fr = "Nom du paramètre : modnonsubposts"
        type = "boolean"

        [main.moderation.moderated]
        ask.en = "Should legit messages be moderated (note: moderators messages will not be moderated)?"
        ask.fr = "Les messages légitimes doivent-ils être modérés (note: les messages des modérateurs ne seront pas modérés)?"
        help.en = "Setting name: moderated"
        help.fr = "Nom du paramètre : moderated"
        type = "boolean"

        [main.moderation.notifymod]
        ask.en = "Should posters get an email when their post is being moderated?"
        ask.fr = "Les auteurs de messages devraient-ils recevoir un courrier électronique lorsque leur message est en cours de modération ?"
        help.en = "Setting name: notifymod"
        help.fr = "Nom du paramètre : notifymod"
        type = "boolean"

    [main.sub]
    name.en = "Subscribers" 
    name.fr = "Abonnés" 
    description.en = "This is a simplified management interface. For advanced options, please refer to the documentation."     
    description.fr = "Il s'agit d'une interface de gestion simplifiée. Pour des options avancées, veuillez vous référer à la documentation." 
 
        [main.sub.add]
        help.en = "A welcome email will be sent to added addresses."
        help.fr = "Un courriel de bienvenue sera envoyé aux adresses ajoutées."
        example = "turtle@sweethome.org"
        ask.en = "Add addresses to the list (one per line)"
        ask.fr = "Ajouter des adresses à la liste (une par ligne)"
        type = "text"

       [main.sub.del]
       help.en = "Addresses will be removed from the list."
       help.fr = "Les adresses seront retirées de la liste."
       example = "turtle@sweethome.org"
       ask.en = "Remove addresses from the list (one per line)"
       ask.fr = "Retirer des adresses de la liste (une par ligne)"
       type = "text"


    # [main.others]
    # name.en = "Other settings"
    # name.fr = "Autres paramètres"

    #     [main.others.prefix]
    #     ask.en = "Prefix for the Subject line of emails"
    #     ask.fr = "Préfixe pour la ligne d'objet des emails"
    #     help.en = "Setting name: prefix"
    #     help.fr = "Nom du paramètre : prefix"
    #     type = "text"
    #     bind = "__INSTALL_DIR__/control/prefix"

    #     [main.others.footer]
    #     ask.en = "Footer content"
    #     ask.fr = "Contenu du pied de page"
    #     help.en = "Setting name: footer"
        # help.fr = "Nom du paramètre : footer"
        # type = "text"
        # bind = "__INSTALL_DIR__/control/footer"
