version = "1.0"

[main]

    [main.general]
        [main.general.closedlist]
        ask.en = "Is the list closed for subscription?"
        type = "boolean"

        [main.general.prefix]
        ask.en = "Prefix for the Subject line of emails"
        type = "string"

    [main.moderation]
        [main.moderation.moderated]
        ask.en = "Should the list be moderated?"
        type = "boolean"

        [main.moderation.moderators]
        ask.en = "List of moderators (one email address per line)"
        type = "text"

