version = "1.0"

[main]

    [main.general]
        [main.general.closedlist]
        ask.en = "Is the list closed for subscription?"
        type = "boolean"

        [main.general.moderated]
        ask.en = "Should the list be moderated?"
        type = "boolean"
