#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "mlmmj"
name = "mlmmj"
description.en = "Mailing List Manager Made Joyful, a simple and efficient mailing list manager."
description.fr = "Gestionnaire de listes de diffusion efficace et simple d'utilisation."
version = "1.4.3~ynh1"
maintainers = [{ name = "Raph", email = "raph@raph" }]

[upstream]
license = "MIT"
website = "https://codeberg.org/mlmmj/mlmmj"
admindoc = "https://codeberg.org/mlmmj/mlmmj"
userdoc = "https://codeberg.org/mlmmj/mlmmj"
code = "https://codeberg.org/mlmmj/mlmmj"

[integration]
yunohost = ">= 11.1"
architectures = "all"
multi_instance = true
ldap = "not_relevant"
sso = "not_relevant"
disk = "1M"
ram.build = "1M"
ram.runtime = "1M"

[install]
  [install.list_name]
  ask.en = "Enter the name of the mailing list"
  ask.fr = "Entrez le nom de la liste de diffusion"
  type = "string"
  pattern.regexp = '^[a-zA-Z0-9.-]+$'
  pattern.error.en = "The name of the list must consist solely of letters, numbers, dots or hyphens."
  pattern.error.fr = "Le nom de la liste doit être composé uniquement de lettres, chiffres, points ou tirets."

  [install.domain]
  ask.en = "Select the domain for the mailing list"
  ask.fr = "Sélectionnez le domaine pour la liste de diffusion"
  type = "domain"
  # choices = "__DOMAINS__"

  [install.language]
  ask.en = "Choose the application language"
  ask.fr = "Choisissez la langue de l'application"
  type = "select"
  choices = ["ast", "cs", "de", "en", "fi", "fr", "gr", "it", "pt", "sk", "zh-cn"]
  default = "en"

  [install.owner]
  ask.en = "Select the owner of the mailing list:"
  ask.fr = "Sélectionnez le propriétaire de la liste de diffusion :"
  help.en = "Owners of the mailing list can be added or removed after the initial setup through the Yunohost administration interface."
  help.fr = "Il est possible d'ajouter ou de supprimer des propriétaires de la liste de diffusion après la configuration initiale via l'interface d'administration de Yunohost."
  type = "user"


[resources]
  [resources.sources.main]
  url = "https://codeberg.org/mlmmj/mlmmj/releases/download/RELEASE_1_4_3/mlmmj-1.4.3.tar.xz"
  sha256 = "dcaee66232fa1d10d9d2352ceb03b05879dfba978368988af585b0697506f4a1"
  format = "tar.xz"
  in_subdir = true

  [resources.data_dir]
  subdirs = ['incoming', 'queue', 'queue/discarded', 'archive', 'text', 'subconf', 'unsubconf', 'bounce', 'control', 'moderation', 'subscribers.d', 'digesters.d', 'requeue', 'nomailsubs.d', 'ynh']
  owner = "list:rwx"
  group = "list:rx"
