#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "mlmmj"
name = "mlmmj"
description.en = "Mailing List Manager Made Joyful, a simple and efficient mailing list manager."
description.fr = "Gestionnaire de listes de diffusion efficace et simple d'utilisation."

version = "1.0~ynh1"

maintainers = ["votre_nom"]

[upstream]
license = "GPL-2.0-or-later"
website = "https://codeberg.org/mlmmj/mlmmj"
demo = "N/A"
admindoc = "https://yunohost.org/packaging_apps"
userdoc = "https://yunohost.org/apps"
code = "https://codeberg.org/mlmmj/mlmmj"
cpe = "N/A"
fund = "N/A"

[integration]
yunohost = ">= 11.1.21"
architectures = "all"
multi_instance = false

ldap = "not_relevant"
sso = "not_relevant"

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/mlmmj"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["fr", "en"]
    default = "en"

    [install.admin]
    type = "user"

    [install.password]
    help.en = "Choose a strong password for the mlmmj admin panel."
    help.fr = "Choisissez un mot de passe fort pour le panneau d'administration de mlmmj."
    type = "password"

[resources]
    [resources.sources]
        [resources.sources.main]
        url = "https://codeberg.org/mlmmj/mlmmj/archive/<tag-version>.tar.gz"
        sha256 = "<sha256sum>"
        # autoupdate.strategy = "latest_github_tag"

    [resources.system_user]
    # ...

    [resources.install_dir]
    # ...

    [resources.data_dir]
    # ...

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    # ...

    [resources.apt]
    packages = "mlmmj"

    [resources.database]
    # ...
