#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    args.owner = "package_checker"
    args.list_email = "list@domain.tld"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    # test_upgrade_from.00a1a6e7.name = "Upgrade from 5.4"
    # test_upgrade_from.00a1a6e7.args.foo = "bar"
